language: go

go:
 - 1.15.x

cache:
 directories:
  - "$GOPATH/pkg/mod"
  - "$HOME/.cache/go-build"

before_script:
 - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.0

script:
 - golangci-lint run -v -c golangci.yml
 - go test -v ./...
